name: Build project

on: [ push ]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      #      - uses: actions/cache@v2
      #        with:
      #          path: C:\Unity Project\Finger gun project\Library 
      #          key: Library-Finger-gun-project-Android
      #          restore-keys: |
      #            Library-Finger-gun-project-
      #            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android # Build an Android .apk standalone app.
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      - uses: game-ci/unity-builder@v2
        with:
          customImage: 'unityci/editor:2020.1.14f1-base-0'